# Version of docker-compose
version: '3'

services:
  # getting postgres DB
  db:
    image: postgres:11.1
    container_name: library-db
    ports:
      - 5432:5433
    environment:
      POSTGRES_USER: ocp
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: troparo
      POSTGRES_INITDB_ARGS: --data-checksums
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - troparo


  # getting library-webservice image
  webservice:
    image: library-webservice
    container_name: library-webservice
    build: .
    ports:
     - 8080:8080
    volumes:
      - logs:/usr/app/resources
    depends_on:
      - db
    networks:
      - troparo

       # getting troparo image
  mailapp:
    image: library_mailapp
    container_name: library_mailapp
    build: ../mail3/.
    ports:
        - 8085:8080
    volumes:
      - logs:/usr/app/resources    
    depends_on:
      - webservice
    networks:
      - troparo


    # getting troparo image
  webapp:
    image: library_webapp
    container_name: library_webapp
    build: ../webo/library/.
    ports:
        - 8090:8080
    volumes:
      - logs:/usr/app/resources
    depends_on:
      - webservice
    networks:
      - troparo


volumes:  
  pg-data:
  logs:

networks:
  troparo:

