package org.troparo.services.connectservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-11T00:25:59.498+01:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://troparo.org/services/ConnectService/", name = "IConnectService")
@XmlSeeAlso({org.troparo.entities.connect.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IConnectService {

    @WebMethod
    @WebResult(name = "invalidateTokenResponseType", targetNamespace = "http://troparo.org/entities/connect", partName = "parameters")
    public org.troparo.entities.connect.InvalidateTokenResponseType invalidateToken(
        @WebParam(partName = "parameters", name = "invalidateTokenRequestType", targetNamespace = "http://troparo.org/entities/connect")
        org.troparo.entities.connect.InvalidateTokenRequestType parameters
    ) throws BusinessExceptionConnect;

    @WebMethod
    @WebResult(name = "getTokenResponseType", targetNamespace = "http://troparo.org/entities/connect", partName = "parameters")
    public org.troparo.entities.connect.GetTokenResponseType getToken(
        @WebParam(partName = "parameters", name = "getTokenRequestType", targetNamespace = "http://troparo.org/entities/connect")
        org.troparo.entities.connect.GetTokenRequestType parameters
    ) throws BusinessExceptionConnect;

    @WebMethod
    @WebResult(name = "checkTokenResponseType", targetNamespace = "http://troparo.org/entities/connect", partName = "parameters")
    public org.troparo.entities.connect.CheckTokenResponseType checkToken(
        @WebParam(partName = "parameters", name = "checkTokenRequestType", targetNamespace = "http://troparo.org/entities/connect")
        org.troparo.entities.connect.CheckTokenRequestType parameters
    ) throws BusinessExceptionConnect;

    @WebMethod
    @WebResult(name = "resetPasswordResponseType", targetNamespace = "http://troparo.org/entities/connect", partName = "parameters")
    public org.troparo.entities.connect.ResetPasswordResponseType resetPassword(
        @WebParam(partName = "parameters", name = "resetPasswordRequestType", targetNamespace = "http://troparo.org/entities/connect")
        org.troparo.entities.connect.ResetPasswordRequestType parameters
    ) throws BusinessExceptionConnect;
}
