
package org.troparo.services.loanservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-11T00:25:59.337+01:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "BusinessLoanFaultType", targetNamespace = "http://troparo.org/entities/loan")
public class BusinessExceptionLoan extends Exception {

    private org.troparo.entities.loan.BusinessLoanFaultType businessLoanFaultType;

    public BusinessExceptionLoan() {
        super();
    }

    public BusinessExceptionLoan(String message) {
        super(message);
    }

    public BusinessExceptionLoan(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public BusinessExceptionLoan(String message, org.troparo.entities.loan.BusinessLoanFaultType businessLoanFaultType) {
        super(message);
        this.businessLoanFaultType = businessLoanFaultType;
    }

    public BusinessExceptionLoan(String message, org.troparo.entities.loan.BusinessLoanFaultType businessLoanFaultType, java.lang.Throwable cause) {
        super(message, cause);
        this.businessLoanFaultType = businessLoanFaultType;
    }

    public org.troparo.entities.loan.BusinessLoanFaultType getFaultInfo() {
        return this.businessLoanFaultType;
    }
}
