package org.troparo.services.bookservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-11T00:25:58.846+01:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://troparo.org/services/BookService/", name = "IBookService")
@XmlSeeAlso({org.troparo.entities.book.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IBookService {

    @WebMethod
    @WebResult(name = "updateBookResponseType", targetNamespace = "http://troparo.org/entities/book", partName = "parameters")
    public org.troparo.entities.book.UpdateBookResponseType updateBook(
        @WebParam(partName = "parameters", name = "updateBookRequestType", targetNamespace = "http://troparo.org/entities/book")
        org.troparo.entities.book.UpdateBookRequestType parameters
    ) throws BusinessExceptionBook;

    @WebMethod
    @WebResult(name = "addCopyResponseType", targetNamespace = "http://troparo.org/entities/book", partName = "parameters")
    public org.troparo.entities.book.AddCopyResponseType addCopy(
        @WebParam(partName = "parameters", name = "addCopyRequestType", targetNamespace = "http://troparo.org/entities/book")
        org.troparo.entities.book.AddCopyRequestType parameters
    ) throws BusinessExceptionBook;

    @WebMethod
    @WebResult(name = "getBookByCriteriasResponseType", targetNamespace = "http://troparo.org/entities/book", partName = "parameters")
    public org.troparo.entities.book.GetBookByCriteriasResponseType getBookByCriterias(
        @WebParam(partName = "parameters", name = "getBookByCriteriasRequestType", targetNamespace = "http://troparo.org/entities/book")
        org.troparo.entities.book.GetBookByCriteriasRequestType parameters
    ) throws BusinessExceptionBook;

    @WebMethod
    @WebResult(name = "BookListResponseType", targetNamespace = "http://troparo.org/entities/book", partName = "parameters")
    public org.troparo.entities.book.BookListResponseType getAllBooks(
        @WebParam(partName = "parameters", name = "BookListRequestType", targetNamespace = "http://troparo.org/entities/book")
        org.troparo.entities.book.BookListRequestType parameters
    ) throws BusinessExceptionBook;

    @WebMethod
    @WebResult(name = "isAvailableResponseType", targetNamespace = "http://troparo.org/entities/book", partName = "parameters")
    public org.troparo.entities.book.IsAvailableResponseType isAvailable(
        @WebParam(partName = "parameters", name = "isAvailableRequestType", targetNamespace = "http://troparo.org/entities/book")
        org.troparo.entities.book.IsAvailableRequestType parameters
    ) throws BusinessExceptionBook;

    @WebMethod
    @WebResult(name = "removeBookResponseType", targetNamespace = "http://troparo.org/entities/book", partName = "parameters")
    public org.troparo.entities.book.RemoveBookResponseType removeBook(
        @WebParam(partName = "parameters", name = "removeBookRequestType", targetNamespace = "http://troparo.org/entities/book")
        org.troparo.entities.book.RemoveBookRequestType parameters
    ) throws BusinessExceptionBook;

    @WebMethod
    @WebResult(name = "getBookByIdResponseType", targetNamespace = "http://troparo.org/entities/book", partName = "parameters")
    public org.troparo.entities.book.GetBookByIdResponseType getBookById(
        @WebParam(partName = "parameters", name = "getBookByIdRequestType", targetNamespace = "http://troparo.org/entities/book")
        org.troparo.entities.book.GetBookByIdRequestType parameters
    ) throws BusinessExceptionBook;

    @WebMethod
    @WebResult(name = "getAvailableResponseType", targetNamespace = "http://troparo.org/entities/book", partName = "parameters")
    public org.troparo.entities.book.GetAvailableResponseType getAvailable(
        @WebParam(partName = "parameters", name = "getAvailableRequestType", targetNamespace = "http://troparo.org/entities/book")
        org.troparo.entities.book.GetAvailableRequestType parameters
    ) throws BusinessExceptionBook;

    @WebMethod
    @WebResult(name = "addBookResponseType", targetNamespace = "http://troparo.org/entities/book", partName = "parameters")
    public org.troparo.entities.book.AddBookResponseType addBook(
        @WebParam(partName = "parameters", name = "addBookRequestType", targetNamespace = "http://troparo.org/entities/book")
        org.troparo.entities.book.AddBookRequestType parameters
    ) throws BusinessExceptionBook;
}
